version: '3.7'
services:
  db:
    image: postgres:14.6-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_DB=komiser
      - POSTGRES_PASSWORD=admin
  app:
    build: .
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - db
volumes:
  postgres-data:
